name: Go CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'  # Update this to match the Go version specified in go.mod

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures the deploy job runs only if the build job is successful
    steps:
    - uses: actions/checkout@v4  # Check out the code again for the deploy stage

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: guibondi
        password: Melani2001@  # Ensure this is set in GitHub Secrets

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: guibondi/simpleapi:latest

    - name: Deploy to Docker for tests
      run: |
        docker pull guibondi/simpleapi:latest
        docker run -d -p 8080:8080 guibondi/simpleapi:latest
